version: "3.8"
services:
  db:
    image: postgres:15.2
    container_name: ai_summarizer_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Maps host port 5432 to container port 5432
    networks:
      - app_net

  web:
    build: .
    container_name: ai_summarizer_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
