version: "3.8"

services:
  db:
    image: postgres:15.2
    container_name: ai_summarizer_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: summarizer_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  web:
    build: .
    container_name: ai_summarizer_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=summarizer_db
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
